### ISSUE TITLE
[Documentation] Add a project description

### ISSUE THREAD

**Issue by oskstr** [oskstr/INDA-Project#1]
Write a short Project Description, using the repo's README.

- [x] Our names
- [x] Programming language
- [x] Graphics library, frameworks, methods used
- [x] Short description (menus, functions, thoughts, etc.)
- [x] Documentation on how to install and use the project (this will evolve)
- [x] Description of classes (preferably with a class diagram)
- [x] How we plan to test our project

**Comment by kittytinythai** [comment]
For now, done!
