### ISSUE TITLE
Restart screen when game ends/game over

### ISSUE THREAD

**Issue by kittytinythai** [oskstr/INDA-Project#37]
- [x] Create pop-up window
- [x] Add labels with **Game Over** or **INDA17 Complete!**
- [x] Message with completed weekly assignments
- [x] Add label with current course (prginda, alginda etc.)

**Comment by oskstr** [comment]
@kittytinythai Could you please elaborate on what you would like to happen with the last two tasks in the list? And how does it differ from how the game currently works?

**Comment by kittytinythai** [comment]
The current implementation was exactly what I meant 😄 good job! 👍
