### ISSUE TITLE
Graph game

### ISSUE THREAD

**Issue by oskstr** [oskstr/INDA-Project#7]
Create the graph game.

- [ ] Create a field of nodes
- [ ] User movements between nodes
- [ ] Get back-tracking working
- [ ] Make Plutten move
- [ ] Add collitions

**Comment by kittytinythai** [comment]
![meme](https://user-images.githubusercontent.com/34159235/39748641-e32463b6-52b0-11e8-9dce-51098060b6ce.jpg)
